//form
export const CHANGE_NICKNAME = "CHANGE_NICKNAME";
export const CHANGE_EMAIL = "CHANGE_EMAIL";
export const CHANGE_IPADRESS = "CHANGE_IP_ADRESS";

//errors
export const HANDLE_NICKAME_ERROR = "SHOW_NICKAME_ERROR";
export const HANDLE_EMAIL_ERROR = "SHOW_EMAIL_ERROR";
export const HANDLE_IPADRESS_ERROR = "SHOW_IPADRESS_ERROR";

//userList
export const ADD_USER = "ADD_USER";
export const DELETE_USER = "DELETE_USER";
export const DELETE_USER_LIST = "DELETE_USER_LIST";

export const SORT_BY_NICKNAME = "SORT_BY_NICKNAME";
export const SORT_BY_EMAIL = "SORT_BY_EMAIL";
export const SORT_BY_IPADRESS = "SORT_BY_IPADRESS";

//dialog
export const SET_DELETE_USERS_LIST_DIALOG = "SHOW_DELETE_USERS_LIST_DIALOG";
export const SET_DELETE_USER_DIALOG = "SHOW_DELETE_USER_DIALOG";